### ISSUE TITLE
Use the Rails logger?

### ISSUE THREAD

**Issue by nz** [omc/bonsai-elasticsearch-rails#1]
We're reporting the initialization, let's reuse the Rails logger if it's available.

**Comment by robsears** [comment]
Added.

**Comment by apraditya** [comment]
The log becomes out in STDOUT instead of to the log files. Is this related?

**Comment by nz** [comment]
@apraditya we do set up a `Logger.new(STDOUT)` to print a few informational messages during configuration, but that should only be when `Rails.logger` is not defined. That's something we can test a little bit better. What version of Rails is your app using?

**Comment by apraditya** [comment]
I'm using the latest version of rails 4.2.
