### ISSUE TITLE
Cannot be installed along with elasticsearch-rails 5.0.1

### ISSUE THREAD

**Issue by yoshinobu-iriguchi** [omc/bonsai-elasticsearch-rails#5]
I need `elasticsearch-rails` / `elasticsearch-model` version >= 5.0.1 installed along with bonsai-elasticsearch-rails. But the latest version of bonsai-elasticsearch-rails, 0.2.0 has following dependencies:

```
elasticsearch-model (~> 0)
elasticsearch-rails (~> 0)
```

They are equivalent to `['>= 0', '< 1']` according to http://guides.rubygems.org/patterns/#pessimistic_version_constraint

Could you please allow versions greater or equal to 5 of elasticsearch-*?

**Comment by robsears** [comment]
Hi there,

Thanks for reaching out. Apologies for the delay in responding. Per the README, the best way to get in touch with us about this repo is via email, using [support@bonsai.io](mailto:support@bonsai.io).

I've pushed out versions of this gem that correspond to the available versions of Elasticsearch. Here's what you can use in your Gemfile:

```ruby
# Elasticsearch 1.x
gem 'bonsai-elasticsearch-rails', '~>1'

# Elasticsearch 2.x
gem 'bonsai-elasticsearch-rails', '~>2'

# Elasticsearch 5.x
gem 'bonsai-elasticsearch-rails', '~>5'

# Elasticsearch 6.x (there is currently no 6.x elasticsearch-rails gem on RubyGems,
# so those need to reference the GitHub repo:
gem 'bonsai-elasticsearch-rails', '~>6'
gem 'elasticsearch-model', github: 'elastic/elasticsearch-rails', branch: '6.x'
gem 'elasticsearch-rails', github: 'elastic/elasticsearch-rails', branch: '6.x'

# Elasticsearch 7.x (in alpha as of this writing)
gem 'bonsai-elasticsearch-rails', '~>7'
gem 'elasticsearch-model', github: 'elastic/elasticsearch-rails', branch: 'master'
gem 'elasticsearch-rails', github: 'elastic/elasticsearch-rails', branch: 'master'
```

A couple quick gotchas:

Without specifying a version of this gem, you'll end up with the latest version of the elasticsearch-rails and elasticsearch-model gems available on RubyGems. That's the 5.x branch as of now:

So simply adding `gem 'bonsai-elasticsearch-rails'` to your Gemfile will also install:

* elasticsearch-api 5.0.5
* elasticsearch-transport 5.0.5
* elasticsearch 5.0.5
* elasticsearch-model 5.1.0 
* elasticsearch-rails 5.1.0

If you want to use the 6.x or 7.x-compatible gems, you will need to specify them in your Gemfile. This will give you the 6.x branch:

```
gem 'bonsai-elasticsearch-rails'
gem 'elasticsearch-model', github: 'elastic/elasticsearch-rails', branch: '6.x'
gem 'elasticsearch-rails', github: 'elastic/elasticsearch-rails', branch: '6.x'
```

And this will give you the 7.x branch:

```
gem 'bonsai-elasticsearch-rails'
gem 'elasticsearch-model', github: 'elastic/elasticsearch-rails', branch: 'master'
gem 'elasticsearch-rails', github: 'elastic/elasticsearch-rails', branch: 'master'
```

Please update your Gemfile accordingly, and run `bundle update bonsai-elasticsearch-rails`. That will get you on whatever version of the gems are best suited for your version of Elasticsearch. If you run into any issues, please send an email to [support@bonsai.io](mailto:support@bonsai.io).
